# workaround: don't print `$git_state` and `$git_status` because of bad fs
# performance in wsl (on ntfs)
format = """
$directory\
$git_branch\
$git_commit\
$hg_branch\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[cmd_duration]
show_milliseconds = true
format = "[$duration]($style) "

[directory]
fish_style_pwd_dir_length = 1
